name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: customerapp-448610
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Step 3: Build and Push Docker Image to GCR
      - name: Build and Push Docker Image
        run: |
          IMAGE=gcr.io/customerapp-448610/newcustomer1:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE

      # Step 4: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy newcustomer1 \
            --image gcr.io/customerapp-448610/newcustomer1:${{ github.sha }} \
            --region us-central1 \
            --platform managed \
            --add-cloudsql-instances customerapp-448610:asia-south1:mysqldb \
            --allow-unauthenticated
